/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OracleReceiver } from "./OracleReceiver";
export type { PaymentProcessor } from "./PaymentProcessor";
